# Generated by Django 2.2.4 on 2022-12-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cad_ciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cad_Ciente',
            new_name='Cad_Cliente',
        ),
    ]
